// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package repository_mock is a generated GoMock package.
package repository_mock

import (
	rates "github.com/ferruvich/go-exchange-rates-api/internal/rates"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepositorer is a mock of Repositorer interface
type MockRepositorer struct {
	ctrl     *gomock.Controller
	recorder *MockRepositorerMockRecorder
}

// MockRepositorerMockRecorder is the mock recorder for MockRepositorer
type MockRepositorerMockRecorder struct {
	mock *MockRepositorer
}

// NewMockRepositorer creates a new mock instance
func NewMockRepositorer(ctrl *gomock.Controller) *MockRepositorer {
	mock := &MockRepositorer{ctrl: ctrl}
	mock.recorder = &MockRepositorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepositorer) EXPECT() *MockRepositorerMockRecorder {
	return m.recorder
}

// CurrentRates mocks base method
func (m *MockRepositorer) CurrentRates(base string) (*rates.BasedRates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentRates", base)
	ret0, _ := ret[0].(*rates.BasedRates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentRates indicates an expected call of CurrentRates
func (mr *MockRepositorerMockRecorder) CurrentRates(base interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentRates", reflect.TypeOf((*MockRepositorer)(nil).CurrentRates), base)
}

// HistoricalRates mocks base method
func (m *MockRepositorer) HistoricalRates(base, start, end string) (*rates.HistoricalRates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HistoricalRates", base, start, end)
	ret0, _ := ret[0].(*rates.HistoricalRates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HistoricalRates indicates an expected call of HistoricalRates
func (mr *MockRepositorerMockRecorder) HistoricalRates(base, start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HistoricalRates", reflect.TypeOf((*MockRepositorer)(nil).HistoricalRates), base, start, end)
}

// SpecificRates mocks base method
func (m *MockRepositorer) SpecificRates(base string, currencies []string) (*rates.BasedRates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpecificRates", base, currencies)
	ret0, _ := ret[0].(*rates.BasedRates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpecificRates indicates an expected call of SpecificRates
func (mr *MockRepositorerMockRecorder) SpecificRates(base, currencies interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpecificRates", reflect.TypeOf((*MockRepositorer)(nil).SpecificRates), base, currencies)
}
